### ISSUE TITLE
Wondering if this will ever be fixed

### ISSUE THREAD

**Issue by tyranno83** [PhasmaExMachina/dc-mod-manager#12]
![Screenshot_20200801-192208](https://user-images.githubusercontent.com/68392351/89113372-7a60c300-d42d-11ea-850e-683beaed6269.png)

Or is this on purpose?

**Comment by PhasmaExMachina** [comment]
Yeah... someone thought putting in lobsters as mods was cute at some point and the automated system picked them up. I've deleted a bunch including this one. Just pushed the fix. Should go through within 20 minutes or so.
