### ISSUE TITLE
Childs not showing when there is less than 10 left

### ISSUE THREAD

**Issue by SilentAndDark** [PhasmaExMachina/dc-mod-manager#6]
When there is less than 10 childs or 10 skins, the next button is greyed out, so you are unable to view them.

**Comment by PhasmaExMachina** [comment]
Thanks for reporting this @SilentAndDark. Any chance you can give me a URL and screenshot that reproduces this issue? Happy to fix it once I figure it out.

**Comment by SilentAndDark** [comment]
Sorry for the late response, I haven't checked github in a while. I don't understand how I can provide a URL, however I can send a screenshot.

**Comment by SilentAndDark** [comment]
Sorry for the late response, I haven't checked github in a while. I had to close and re-open the issue because for some reason the comment button was disabled

I don't know how to provide you with a URL, but I can gladly send a screenshot. This bug occurs with any skin, mod, character, ect. when there's less than 10 to be viewed. However, I've also found that if you search for something with less than 10 skins/characters/mods, you can change pages and go next infinitely.

**Comment by SilentAndDark** [comment]
![20200718_042530](https://user-images.githubusercontent.com/68069196/87835429-e92b1180-c8ae-11ea-9eb9-5848a45b0481.jpg)
![20200718_042624](https://user-images.githubusercontent.com/68069196/87835431-eaf4d500-c8ae-11ea-9230-7f6864417d3e.jpg)
