### ISSUE TITLE
Make nude mod for this character please

### ISSUE THREAD

**Issue by nguyennd125** [PhasmaExMachina/dc-mod-manager#7]
Can you guys make the nude mod for werewolf please

**Comment by PhasmaExMachina** [comment]
Hi @nguyennd125 the best place to make requests for mods is on the [discord community](https://discord.gg/2vew9te).That said, there are already some topless ones, but not totally nude at https://phasmaexmachina.github.io/destiny-child-mods-archive/characters/c216.
