### ISSUE TITLE
Feature Request: Batch Apply "Uncensor" Pack

### ISSUE THREAD

**Issue by CrashMD** [PhasmaExMachina/dc-mod-manager#9]
So far the mod manager works great (Google Pixel 2XL), but the feature I'm looking for is an easy way to apply the original Korean "uncensored" art with a simple button press.

**Comment by tyranno83** [comment]
The only way I know how is to use a root browser. I actually did it earlier today

**Comment by PhasmaExMachina** [comment]
>I'm looking for is an easy way to apply the original Korean "uncensored" art with a simple button press.

This feature is planned! Stay tuned. 😁 

>The only way I know how is to use a root browser. I actually did it earlier today

You don't need a root browser to do this, just the uncensored PCK files that have been pre-converted to Global that you copy into the assets/child folder. No root access required.

When the new feature is ready in the app, it will be a matter of clicking a button and waiting for the files to install.

**Comment by PhasmaExMachina** [comment]
This has been done or a while now but I forgot to close it. See Lists > Uncensored > Install all mods in list
